"""initial schema

Revision ID: 25d95d551151
Revises: 
Create Date: 2026-04-28 12:25:01.455646

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '25d95d551151'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('cached_from_id', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cached_from_id'], ['llm_calls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_prompt_hash'), ['prompt_hash'], unique=False)

    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.String(length=128), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('resolution_source', sa.Text(), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_markets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_condition_id'), ['condition_id'], unique=True)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='pipeline_run_status'), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_started_at'), ['started_at'], unique=False)

    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('midpoint', sa.Float(), nullable=True),
    sa.Column('best_bid', sa.Float(), nullable=True),
    sa.Column('best_ask', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('depth_bid_usd', sa.Float(), nullable=True),
    sa.Column('depth_ask_usd', sa.Float(), nullable=True),
    sa.Column('volume_24h_usd', sa.Float(), nullable=True),
    sa.Column('raw_orderbook', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_market_id'), ['market_id'], unique=False)

    op.create_table('research_dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('resolution_criteria_verbatim', sa.Text(), nullable=False),
    sa.Column('key_facts', sa.JSON(), nullable=False),
    sa.Column('base_rate_analysis', sa.Text(), nullable=False),
    sa.Column('recent_news', sa.JSON(), nullable=False),
    sa.Column('expert_views', sa.JSON(), nullable=False),
    sa.Column('uncertainty_sources', sa.JSON(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('llm_call_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_dossiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_dossiers_market_id'), ['market_id'], unique=False)

    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('YES', 'NO', 'INVALID', name='resolution_outcome'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resolutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resolutions_market_id'), ['market_id'], unique=True)

    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('forecaster_prompt_version', sa.String(length=32), nullable=False),
    sa.Column('forecaster_probability', sa.Float(), nullable=False),
    sa.Column('forecaster_confidence_low', sa.Float(), nullable=False),
    sa.Column('forecaster_confidence_high', sa.Float(), nullable=False),
    sa.Column('forecaster_reasoning', sa.Text(), nullable=False),
    sa.Column('forecaster_key_drivers', sa.JSON(), nullable=False),
    sa.Column('forecaster_llm_call_id', sa.Integer(), nullable=False),
    sa.Column('critic_prompt_version', sa.String(length=32), nullable=True),
    sa.Column('critic_adjusted_probability', sa.Float(), nullable=True),
    sa.Column('critic_critique', sa.Text(), nullable=True),
    sa.Column('critic_flagged_untradeable', sa.Boolean(), nullable=False),
    sa.Column('critic_llm_call_id', sa.Integer(), nullable=True),
    sa.Column('final_probability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('final_probability >= 0.0 AND final_probability <= 1.0', name='ck_final_probability_range'),
    sa.CheckConstraint('forecaster_probability >= 0.0 AND forecaster_probability <= 1.0', name='ck_forecaster_probability_range'),
    sa.ForeignKeyConstraint(['critic_llm_call_id'], ['llm_calls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dossier_id'], ['research_dossiers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['forecaster_llm_call_id'], ['llm_calls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_market_id'), ['market_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('YES', 'NO', name='trade_side'), nullable=False),
    sa.Column('intended_price', sa.Float(), nullable=False),
    sa.Column('intended_size_usd', sa.Float(), nullable=False),
    sa.Column('kelly_fraction_used', sa.Float(), nullable=False),
    sa.Column('edge_points', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'FILLED_PAPER', 'REJECTED', 'CLOSED', name='trade_status'), nullable=False),
    sa.Column('realized_pnl_usd', sa.Float(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_market_id'), ['market_id'], unique=False)

    op.create_table('trade_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_midpoint', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_marks_marked_at'), ['marked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_marks_trade_id'), ['trade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_marks_trade_id'))
        batch_op.drop_index(batch_op.f('ix_trade_marks_marked_at'))

    op.drop_table('trade_marks')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_market_id'))

    op.drop_table('trades')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_market_id'))

    op.drop_table('forecasts')
    with op.batch_alter_table('resolutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resolutions_market_id'))

    op.drop_table('resolutions')
    with op.batch_alter_table('research_dossiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_dossiers_market_id'))

    op.drop_table('research_dossiers')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_snapshots_market_id'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_captured_at'))

    op.drop_table('market_snapshots')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_started_at'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_markets_condition_id'))
        batch_op.drop_index(batch_op.f('ix_markets_category'))

    op.drop_table('markets')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_prompt_hash'))

    op.drop_table('llm_calls')
    # ### end Alembic commands ###
